# Generated by Django 3.0.2 on 2025-02-15 11:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ckdApp', '0002_auto_20200205_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ckdmodel',
            old_name='Blood_Glucose_Random',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='ckdmodel',
            old_name='Blood_Urea',
            new_name='ca',
        ),
        migrations.RenameField(
            model_name='ckdmodel',
            old_name='Packed_cell_volume',
            new_name='cp',
        ),
        migrations.RenameField(
            model_name='ckdmodel',
            old_name='Serum_Creatine',
            new_name='exang',
        ),
        migrations.RenameField(
            model_name='ckdmodel',
            old_name='White_blood_count',
            new_name='oldpeak',
        ),
        migrations.AddField(
            model_name='ckdmodel',
            name='thalach',
            field=models.FloatField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
